// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK4BoRRtaJd3qtjjkaMcWMjdeyty1xNSk',
    appId: '1:180545044888:web:b862926a4a53edfb47ebed',
    messagingSenderId: '180545044888',
    projectId: 'shutup-ba773',
    authDomain: 'shutup-ba773.firebaseapp.com',
    storageBucket: 'shutup-ba773.appspot.com',
    measurementId: 'G-2JEEN41V8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkWAFK2y4_-r-h5TmNHmxIT6oApMSoI7E',
    appId: '1:180545044888:android:04d56e7c312f51d047ebed',
    messagingSenderId: '180545044888',
    projectId: 'shutup-ba773',
    storageBucket: 'shutup-ba773.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIfWh7YFwzfoNWALg4WxtyE8brniIWVUM',
    appId: '1:180545044888:ios:c8b9061012a6620c47ebed',
    messagingSenderId: '180545044888',
    projectId: 'shutup-ba773',
    storageBucket: 'shutup-ba773.appspot.com',
    iosBundleId: 'com.example.shutup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIfWh7YFwzfoNWALg4WxtyE8brniIWVUM',
    appId: '1:180545044888:ios:b3a1312394c4a15347ebed',
    messagingSenderId: '180545044888',
    projectId: 'shutup-ba773',
    storageBucket: 'shutup-ba773.appspot.com',
    iosBundleId: 'com.example.shutup.RunnerTests',
  );
}
